### ISSUE TITLE
Update this for CUDA 11.x

### ISSUE THREAD

**Issue by eyalroz** [jeremad/cuda-travis#4]
Can you please update .travis.yml with the details for CUDA 11.0, 11.1 and 11.2?

**Comment by jeremad** [comment]
Hello, sorry for the delay, I'll have a look

**Comment by eyalroz** [comment]
@jeremad : Well? ...

**Comment by jeremad** [comment]
Patches are welcome

**Comment by jeremad** [comment]
I had a quick look, because I am nice. This is not as easy as I thought. here are some basic commands to install the latest CUDA (cuda 11.4 at the time of writing) on focal.
```bash
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
sudo apt-get -y install cuda
```
You can probably customize your `travis.yml` with all of that.
In the meantime, Travis CI is basically dead, I would advise to switch to GH actions, and use this https://github.com/marketplace/actions/cuda-toolkit
I am going to archive this repo.

Regards
